locations = ["Greece", "Japan", "China", "France", "UK"]
print (locations)
print (sorted(locations))
print (locations)
print (sorted(locations, reverse=True))
print (locations)
locations.reverse()
print (locations)
locations.reverse()
locations.remove(sorted(locations)[0])
print (locations)
locations.sort()
print (locations)
locations.sort(reverse=True)
print (locations)